### PR TITLE
Adding matcher option.

### PR DESCRIPTION
**Pull request by lucas-issa**

### CODE REVIEW

**Comment by pbastowski** [comment]
Good idea! Thanks.
I will merge it when I get back from holidays.

**Comment by lucas-issa** [comment]
Hi @pbastowski.
Did you came back from holidays?
Are you planning to do the merge and publish?

**Comment by pbastowski** [comment]
Yeah, I'm back ages ago :) Sorry, forgot totally about this.

Now, the only thing I have to do is to find a Meteor project that I still have available at the correct version to do this.

**Comment by lucas-issa** [comment]
Thank you very much!

**Comment by pbastowski** [comment]
@lucas-issa I have merged and pushed v0.0.6. I have no way to test it right now, unfortunately. Could you please let me know if it works for you.

Oh, I updated the http-proxy package to its latest version. I hope that was not a mistake.

**Comment by lucas-issa** [comment]
Unfortunately it didn't work.
First asked for http-proxy dependency. 
I added this dependency and after that happened the following error: 
TypeError: Package.describe is not a function

**Comment by pbastowski** [comment]
I just tested the new package and it works for me. I am using Meteor 1.5.2.2 with the following proxy config

    DevProxy.addProxy('/api/', 'http://localhost:8080')

Also, I did not have to install http-proxy manually.

Below is a log of my test meteor app running and responding to proxy requests (the app name is proxy)

```
> proxy@ start /Users/paul/dev/meteor/proxy
> meteor run

[[[[[ ~/dev/meteor/proxy ]]]]]

=> Started proxy.
   [HMR] Dev server listening on port 3003
=> Started MongoDB.
I20171004-22:27:03.074(2)? Proxy config:
I20171004-22:27:03.134(2)?  {
I20171004-22:27:03.135(2)?     "source": "/api/",
I20171004-22:27:03.135(2)?     "target": "http://localhost:8080",
I20171004-22:27:03.136(2)?     "exactMatch": false
I20171004-22:27:03.136(2)? }
=> Started your app.

=> App running at: http://localhost:3000/
I20171004-22:27:08.491(2)? proxying /api/user  to:  http://localhost:8080
I20171004-22:27:18.753(2)? proxying /api/user  to:  http://localhost:8080
```

**Comment by lucas-issa** [comment]
Something is wrong with my environment. I downgrade to 0.0.5 version and happened the same error. It was working with local package version. I will look with more care here. 
I am also using Meteor 1.5.2.2.

**Comment by pbastowski** [comment]
Sounds like you're almost there. I am going to sleep now :)

**Comment by lucas-issa** [comment]
Now it's working. Sorry for the wrong alarm.
I renamed the local directory from packages to packages_ and this was the problem. When I moved away the packages_ directory, the problem was solved.
Thanks one more time.

**Pull request merged**
